/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install. It is committed here so
// TypeScript has the right ambient types before the first local dev run.
